import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'models/summary.dart';
import 'models/user_preferences.dart';
import 'utils/theme.dart';
import 'utils/constants.dart';
import 'screens/splash/splash_screen.dart';
import 'screens/onboarding/onboarding_screen.dart';
import 'screens/home/home_screen.dart';
import 'screens/chat/chat_screen.dart';
import 'screens/camera/camera_screen.dart';
import 'screens/analytics/analytics_screen.dart';
import 'screens/history/history_screen.dart';
import 'screens/settings/settings_screen.dart';
import 'screens/auth/login_screen.dart';
import 'providers/preferences_provider.dart';
import 'services/auth_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Hive init
  await Hive.initFlutter();
  Hive.registerAdapter(SummaryAdapter());           // generated by build_runner
  Hive.registerAdapter(UserPreferencesAdapter());   // generated by build_runner
  await Hive.openBox<Summary>(AppConstants.hiveBoxHistory);
  await Hive.openBox<UserPreferences>(AppConstants.hiveBoxSettings);
  await Hive.openBox(AppConstants.hiveBoxAuth);

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor:          Colors.transparent,
    statusBarIconBrightness: Brightness.light,
    statusBarBrightness:     Brightness.dark,
  ));

  runApp(const ProviderScope(child: BrieflyApp()));
}

class BrieflyApp extends ConsumerWidget {
  const BrieflyApp({super.key});
  
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final prefs = ref.watch(preferencesProvider);
    
    return MaterialApp(
      title: AppConstants.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: prefs.isDarkMode ? ThemeMode.dark : ThemeMode.light,
      initialRoute: '/splash',
      routes: {
        '/splash':     (_) => const SplashScreen(),
        '/login':      (_) => const LoginScreen(),
        '/onboarding': (_) => const OnboardingScreen(),
        '/home':       (_) => const HomeScreen(),
        '/chat':       (_) => const ChatScreen(),
        '/camera':     (_) => const CameraScreen(),
        '/analytics':  (_) => const AnalyticsScreen(),
        '/history':    (_) => const HistoryScreen(),
        '/settings':   (_) => const SettingsScreen(),
        // Note: Profile screen added via MaterialPageRoute in settings usually,
        // but we can register it here if needed.
      },
    );
  }
}